config/routes.rb
Rainforest::Application.routes.draw do

  get "reviews/show"

  get "reviews/new"

  get "reviews/edit"

  
  resources :products do
    resources :reviews, except: [:index]
  end
  resources :users, only: [:new,:create]
  resources :sessions, only: [:new,:create,:destroy]

  root :to => "products#index"

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :picture, :price

  validates_presence_of :description, :name, :picture, :price

  validates :picture, format: {with: %r{\.(png|jpg|gif)$}i, messsage: "Pic format must be png/jpg/gif!"}

  has_many :reviews
  has_many :users, through: :reviews

  def formated_price
  	sprintf("%.2f",price)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :comment, :product_id, :user_id

  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :name

  has_secure_password

  validates_presence_of :password_digest, on: :create

  validates :name, presence: true

  has_many :reviews
  has_many :products, :through => :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Log in!"
  		redirect_to new_session_path
  	end
  end

  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_filter :get_product_by_id, only: [:show,:edit,:destroy,:update]
  before_filter :ensure_logged_in, only: [:show]
  def index
    @products = Product.all
    respond_to do |format|
      format.html #index.html.erb
      format.json { render json: @products}
    end
  end

  def show
    if current_user
      @review = @product.reviews.build
    end
    
    respond_to do |format|
      format.html #show.html.erb
      format.json { render json: @product }
    end
  end

  def new
    @product = Product.new
    respond_to do |format|
      format.html #new.html.erb
      format.json { render json: @product}
    end
  end

  def create
    @product = Product.new(params[:product])
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Save process completed!" }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { 
          flash.now[:notice]="Save proccess coudn't be completed!" 
          render :new 
        }
        format.json { render json: @product.errors, status: :unprocessable_entity}
      end
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.json { render json: @product}
    end
  end

  def update
    respond_to do |format|  
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: "Update process completed!" }
        format.json {  head :no_content }
      else 
        format.html {
          flash.now[:notice]= "Update proccess coudn't be completed!"
          render :edit
        }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_path }
      format.json { head :no_content }
    end
  end

  private

  def get_product_by_id
    @product = Product.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  before_filter :load_product
  before_filter :ensure_logged_in, only: [:edit,:create,:show,:update,:destroy]

  def show
  	@review = Review.find(params[:id])
  end

  def new
  end

  def create
  	@review = @product.reviews.build(params[:review])
    @review.user_id = current_user.id
    binding.pry
  	if @review.save
  		redirect_to @product, notice: "Review created successfully"
  	else 
  		render :show
  	end
  end

  def destroy
  	@review = Review.find(params[:id])
  	@review.destroy
  end

  def edit
  end

  private

  def load_product
  	@product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:notice] = "Invalid email or password"  
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
  		redirect_to products_path, notice: "Signed up!"
  	else
 		 render :new
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:notice] %>
		<p id="notice"><%= flash[:notice] %></p>
		<% end %>
	<% if flash[:alert] %>
		<p id="alert"> flash[:alert] </p>
	<% end %>

	<%= yield %>
	<p class="userinfo">
		<% if current_user %>
			Signed in as <%= current_user.name %>. <%= link_to "Log out", session_path("current"), method: :delete %>
		<% else %>
		 <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
	</p>
</body>
</html>

app/views/products/_form.html.erb
<% if flash %>
  <ul>
  <% flash.each do |name,msg| %>
    <li class=<%= name %>>  <%= msg %> </li> 
  <% end %>
  </ul>

<% end %>

<% if @product.errors.any? %>
  <div id="errors">
    <h2> <%= pluralize(@product.errors.count, "error") %> failed </h2>
    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <%  end %>
    </ul>
  </div>
<% end %>
<%= form_for @product do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<%= render 'form' %>

app/views/products/index.html.erb
<h1>Products#index</h1>
<% @products.each do |product| %>
	<p> <%= link_to product.name, product %> </p>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p> <%= @product.name %></p>

<% if current_user %>

  <h3>Reviews</h3>

  <p>Reviews for <%= @product.name %></p>

  <% @product.reviews.each do |review| %>
    <p>

      <%= review.comment %>
      <br>
      <% if review.user != nil %>
        <em> by <%= review.user.name %></em>
        Added on: <%= review.created_at %>
      <% end %>
    </p>
  <% end %>

<h4>New Review</h4>

  <%= form_for([@product, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 


<% end %>



<%= link_to "Edit", edit_product_path(@product) %>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up!</h1>
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
	<div class="errors">
		<h2>Form is invalid:</h2>
		<ul>
			<% for message in @user.errors.full_messages %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="field">
		<%= f.label :name %> <br/>
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :email %> <br/>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %> <br/>
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation %> <br/>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions"> <%= f.submit %> </div>
<% end %>